variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - test

.restrict: &restrict
  only:
    - master
    - /^.*-ci$/
    - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /@skip-ci/

.job-debian:
  image: debian:stretch
  <<: *restrict

.build-debian:
  extends: .job-debian
  stage: build
  before_script:
    - env
    - apt-get update
    - apt-get install -y build-essential m4 $DEBIAN_PKGS
  script:
    - env
    - make help
    - make

.check-debian:
  extends: .job-debian
  stage: test
  before_script:
    - env
    - apt-get update
    - apt-get install -y build-essential m4 python $DEBIAN_PKGS
  script:
    - env
    - make help
    - make
    - make check-ci
    - make check-msg-schema

build-debian-gcc:
  extends: .build-debian

build-debian-clang:
  extends: .build-debian
  variables:
    DEBIAN_PKGS: clang
    CC: clang

build-debian-gcc-lp:
  extends: .build-debian
  variables:
    DEBIAN_PKGS: liblpsolve55-dev
    USE_LPSOLVE: "yes"
    LPSOLVE_LDFLAGS: "-llpsolve55"


check-debian-gcc:
  extends: .check-debian

check-debian-clang:
  extends: .check-debian
  variables:
    DEBIAN_PKGS: clang
    CC: clang

check-debian-gcc-double:
  extends: .check-debian
  variables:
    USE_DOUBLE: "yes"
